version: '3.8'
services:
    app:
        build:
            context: docker
            dockerfile: Dockerfile
            network: host
        container_name: '${CONTAINER_NAME}'
        restart: unless-stopped
        ports:
            - '${APP_PORT:-80}:80'
        volumes:
            - '.:/var/www/html'
        networks:
            - mangg-network
networks:
    mangg-network:
        external: true
